### ISSUE TITLE
I did the Part 3 challenge myself in Ubuntu 21.10. Here are the issues I faced and how I fixed it. 

### ISSUE THREAD

**Issue by Sgt-Miller** [glibg10b/ltt-linux-challenge-issues#1]
Distro - Ubuntu 21.10, default GNOME 40.4 with Wayland
Hardware - Intel 9300H + Nvidia 1650 with Intel/Nvidia "On demand" mode turned on (which is the default). 

1) Copy paste to another drive (Ubuntu to Windows drive)
Done after disabling fastboot   
https://askubuntu.com/questions/880443/dual-boot-cant-move-files

2) Sign pdf document
Method 1 (adding actual image) - done using Libre Office Draw. It supports editing PDFs.  
Method 2 (digital signature) - Didn't do myself, but reviews say it works. 
                           
3) Export chart from Excel
Done without issues, I did not face the border issue mentioned in video. 

4) Add new font 
Just click on install. 
Install gnome-tweaks to change system font. 

5) Print Word Document
I don't have printer, but it should work anyway. 

6) Compress file - Done. Wish progress bar was more detailed (Nautilus). Its just a circle getting filled up. 

7) Take Screenshot 
Works great. 

8) Make a shortcut 
This is not available by default! You have to change settings : 
Nautilus -> Preferences -> Create link
After that you can do shortcuts. This should be on by default!

9) Connect a network share
I just logged in to Google and use a common account. Nautilus nicely mounts Google Drive. 

10) Setup Discord to work on startup - Done. Used gnome-tweaks to create startup. 

11) 4k playback is not smooth on Firefox/Brave. Windows much faster. Something to do with hardware acceleration?

12) watch HDR content - don't think its possible now but devs are working on this. 

Bonus - recording videos using OBS. I was on Wayland, so got black screen. Looks like apt package doesn't have latest update. 
I installed via snap and it worked perfectly. 

Overall Score - 10/12 (after applying some fixes).

**Comment by Sgt-Miller** [comment]
To summarise, here are some suggestions to developers -
1) If Fastboot is turned on in Windows, the partition is mounted as read-only in Ubuntu. When copying, the error message says "no permission". Please make the error message more descriptive, like for NTFS systems it can say "It was mounted in read-only mode. To write to disk, ensure fast boot is disabled. 

2) Please turn on "Create link" option in Nautilus by default. Or provide a more straightforward way to turn it on. Or provide creating shortcut by drag+ctrl+shift. 

3) I think gnome-tweaks should be installed by default. User shouldn't have to install an extra tool to change system fonts and to create startup programs. 

4) I think both Brave and Firefox are having issues with hardware acceleration. I don't know much about it. 

Conclusion : I'm actually quite happy overall. Because after applying the fixes, most of it worked without issues. I just think that most fixes should be applied by default.

**Comment by glibg10b** [comment]
Thanks for sharing, updated.

**Comment by not-a-dev-stein** [comment]
> I think gnome-tweaks should be installed by default. User shouldn't have to install an extra tool to change system fonts and to create startup programs.

At least temporarily this is a good solution, but for the long run it's best for them to implement everything that makes sense into the settings app, like they reccently did with the multitasking panel in GNOME 41. I'd love to see specially more mouse/touchpad options in the mouse/touchpad section (because god, I hate mouse acceleration), startup apps and font management in particular.

> I think both Brave and Firefox are having issues with hardware acceleration. I don't know much about it.

It's a problem with all browsers currently, unfortunately. None of them on Linux ship with hardware video decoding by default. Firefox is the less hard one to do so, all you need is to tick a couple of flags in about:config (soon to be only one flag, as it currently is on Nightly), while Chrome and Chromium currently have no way to make it work with Wayland after implementing Ozone by default, which has no support for VAAPI on Wayland still. And I don't think any of them have any support for NVIDIA's VDPAU.

**Comment by wooque** [comment]
@Sgt-Miller 
>4k playback is not smooth on Firefox/Brave. Windows much faster. Something to do with hardware acceleration?
Yes, hardware acceleration is not enabled in any browser by default because it's not as stable as on Windows or Mac, but it should not be a problem to enable it, consult Arch wiki as always, it works great on my machine.
https://wiki.archlinux.org/title/Chromium#Hardware_video_acceleration
https://wiki.archlinux.org/title/Firefox#Hardware_video_acceleration

**Comment by raibtoffoletto** [comment]
Thanks for sharing! I was thinking in doing the same after watching the part 3 today.

I agree with mostly everything you said, but I don't think tweaks need to be installed by default. On PopOs there are tools for managing startup and extensions by default, this is just a lapse on ubuntu's part but easily overcome.

BTW another way to install fonts is just to create a `~/.fonts` dir and put anything you want there. I even have it in sync with other devices so all get my huge font collection.

**Comment by jtojnar** [comment]
@raibtoffoletto  `~/.fonts` is [deprecated](https://gitlab.freedesktop.org/fontconfig/fontconfig/-/blob/8d3425b8b80bd661efe6763bab508af2d8a265ef/fonts.conf.in#L30-31), `~/.local/share/fonts` is the standard location.

**Comment by raibtoffoletto** [comment]
> @raibtoffoletto `~/.fonts` is [deprecated](https://gitlab.freedesktop.org/fontconfig/fontconfig/-/blob/8d3425b8b80bd661efe6763bab508af2d8a265ef/fonts.conf.in#L30-31), `~/.local/share/fonts` is the standard location.

Really!? Thanks for the heads up, will need to move my structure soon...

**Comment by jtojnar** [comment]
Well, it has been deprecated for years (the XDG Base Directory Specification has been [introduced in 2003](https://gitlab.freedesktop.org/xdg/xdg-specs/-/commits/master/basedir)) and the old location is still widely used so I do not see it being removed any time soon. But migrating is still a good idea, if only to have a slightly cleaner home directory (unfortunately, there [still far too many apps polluting it](https://wiki.archlinux.org/title/XDG_Base_Directory) to achieve full purity).

**Comment by glibg10b** [comment]
Reopening because this evolved into a discussion
