### ISSUE TITLE
Refresh Button "Missing" in Dolphin

### ISSUE THREAD

**Issue by ptredhead** [glibg10b/ltt-linux-challenge-issues#12]
The user was unable to locate the **refresh** action in the menu system [View -> Refresh (F5)].

The refresh action is not in the right-click menu.
The refresh action is not on the toolbar.

Recommendations:
1.  Add "Refresh" icon to the toolbar as default.  I also recommend adding the "Home" icon to the toolbar as well to duplicate the default functions of a web browser ie (Back, Forward, Refresh, Home).  This may make it easier especially for new users to navigate the Linux file system.
2. Add "Refresh" to the right click menu.

I have configured my own Dolphin toolbar thusly:
![image](https://user-images.githubusercontent.com/14139814/144761292-22458f3b-664f-4e22-b73b-45c788551b77.png)

Steps to add "Refresh" and "Home" icons to the toolbar:
1. Using the menu system go to "Tools > Configure Toolbars..." and use the pop-up dialogue to modify the toolbar.
     OR
   Right click on the toolbar and select "Configure Toolbars..." from the right click menu.
2. Search for and select "Refresh" on the "Available actions:" list on the left and using the arrows in the middle of the panel, move "Refresh" to the "Current actions:" list on the right and adjust its position.
![image](https://user-images.githubusercontent.com/14139814/144761704-db700a0f-9714-497c-857a-7eadb39d39aa.png)
2. Remove the text beside the icon by clicking on the "Change Text..." button found beneath the list "Current actions:" and checking the option "Hide text when toolbar shows text alongside icons".
![image](https://user-images.githubusercontent.com/14139814/144762014-7d4d79b7-52f1-437c-bac5-d46c1fcd3038.png)

**Comment by dm2912** [comment]
I think part of the cause of this as well is that KDE by default uses global menus. 

The refresh option is very easily accessed on the view menu, and even a new user would check something like View and of course once they do and see refresh they will also see the tooltip telling them that f5 does the same thing

but KDE moving everything to global menus and hamburger on taskbar hides things away (another reason maybe KDE is not a great DE for a beginner)

**Comment by Fuzzi99** [comment]
GNOME also hides literally everything in a hamburger menu with no hints that it's a menu unless you've used android in the last 5 years.

(Because I use the Global Menu Plasmoid in my top panel I don't have a menu on any window so can't double check to see what menus KDE apps have by default but when I first installed on my desktop it had actual named menus at the top of the window)

**Comment by glibg10b** [comment]
I didn't include it as an issue because there's already multiple ways to refresh. I'll add an item that references this issue.
