### ISSUE TITLE
About "Show Desktop" on KDE

### ISSUE THREAD

**Issue by Mitsunee** [glibg10b/ltt-linux-challenge-issues#13]
"Show Desktop" and "Minimize All Windows" are two separate things in KDE. I found a hotkey for "Show Desktop" in System Settings → Shortcuts → Global Shortcuts → Plasma, but none for "Minimize All Windows" (only to "activate" the existing widget for that function). Pretty sure this would be a "won't fix".

**Comment by sdwvit** [comment]
If it is possible to trigger from terminal, then it should be possible to do in shortcuts

**Comment by glibg10b** [comment]
You just have to right-click "Show Desktop", click "Show Alternatives..." and change it to "Minimize All Windows". It doesn't change the keyboard shortcut, though.
