### ISSUE TITLE
Regarding the KDE Settings situation

### ISSUE THREAD

**Issue by sergeant-savage** [glibg10b/ltt-linux-challenge-issues#16]
# Unifying the Plasma Settings
Presently on Plasma, (On Manjaro KDE mind you, I can't speak for other Plasma distros) you can reach settings both in the main settings application, and separately by searching for them individually. I think that Linus' concerns are valid, and instead of opening up a separate window for a specific settings page, it should just open that page in the main settings manager.
## Separate Settings Window
![Separate](https://user-images.githubusercontent.com/63070761/144772463-2bda7678-4936-48e5-81ce-4b90d52a98b6.png)
## Primary Settings Window
![Unified](https://user-images.githubusercontent.com/63070761/144772547-7220d89d-9d72-450f-b024-47be0d1425ae.png)
## Both open at same time
![Both](https://user-images.githubusercontent.com/63070761/144772638-b0da7675-c369-4ceb-bb87-b9582c43d541.png)

**Comment by sdwvit** [comment]
Valid point, but I guess it implies single settings window instance, which may seem broken for people who are used to this behavior

**Comment by PreyK** [comment]
I think this isn’t the main problem but rather KDE’s system settings itself.
There’s just so many options that you just rather give up and leave it.
Like changing themes wich is just a mess imo.
(https://www.reddit.com/r/kde/comments/a1bzhc/how_do_you_fully_change_the_kde_theme/?utm_source=share&utm_medium=ios_app&utm_name=iossmf)

Or just menu elements being redundant and illogical wich just makes the whole ux feel bloated. Like just take a look at this: 
![image](https://user-images.githubusercontent.com/1968543/144815519-4f5ab66b-497a-45f4-b3f7-d91f50fb6127.png)
Under personalization there’s Online Accounts in the main menu wich could just go under the User menu (per user online accounts) or Notifications wich sould be a “system” setting not personalization imo.
Also region settings under personalization? Shouldn’t that be it’s own category?

If KDE is serious about “world domination” there’s just so much stuff they still need to do.
https://pointieststick.com/category/world-domination/

I use linux daily on my laptop but I just can’t KDE.
This is just my 2 cents from a “windows gamer” mindset, don’t cancel me xd

**Comment by fabianski7** [comment]
> I think this isn’t the main problem but rather KDE’s system settings itself.

This has been discussed for some time among KDE developers and designers. Look: https://invent.kde.org/plasma/systemsettings/-/issues/13

![Appearance](https://user-images.githubusercontent.com/47755037/144842490-b38a0b32-023a-4b4e-8a73-afae9e32f868.png)

**Comment by PreyK** [comment]
> This has been discussed for some time among KDE developers and designers. Look: https://invent.kde.org/plasma/systemsettings/-/issues/13

OH MY GOD PLEASE YES!!!!
This looks beautiful!
Was out of the loop on KDE stuff as I don't use it anymore, so awesome to see they working on this.
Will definitely take a look into it, thanks!

**Comment by sergeant-savage** [comment]
> This has been discussed for some time among KDE developers and designers. Look: https://invent.kde.org/plasma/systemsettings/-/issues/13
Brilliant! Also, after further testing, settings *do* open up in the main settings window, with the exception of any settings in the "Manjaro" category. Upon further digging (rewatching the video), it seems that Linus was struggling with managing audio settings, because he was trying to configure the volume **applet** and not volume in general, which can be done through the applet (not the applet settings, mind you), and through the main system settings window. Seen here:
![image](https://user-images.githubusercontent.com/63070761/144952639-c6fd26cf-86bc-4741-8454-5ffcd75e91ee.png)
It also doesn't help that upon clicking the applet, the gear present will take you to the settings for the *applet* and not the actual audio settings page in the system settings. You can access these settings through the applet, but it is tucked away in a menu called "more actions", I think the underlying problem is firstly, the fact that the concept of applets and widgets, and how they can be individually configured, added to the desktop, and otherwise personalized is not well explained in a fresh Plasma system. At least in my opinion, Plasma needs some kind of tour app, like GNOME's. Secondly, I think that the behavior of the gears in the widgets needs to present a menu for both applet configuration and actual configuration of the settings when both are present. This should be the case for widgets like the volume widget, where it is changing an actual setting. For other widgets, like the weather widget, which isn't modifying anything, the gear should just go to the applet configuration instead. Glad to see they are tidying up the main system settings app though! TL;DR: Settings for Plasma applets that can control actual settings should make it clear that you are changing **applet** settings and not actual settings.
