### ISSUE TITLE
Best distro for gaming is a very subjective matter. I dont think it is fixable

### ISSUE THREAD

**Issue by fleshin** [glibg10b/ltt-linux-challenge-issues#2]
Second google hit (tomsguide) seems pretty decent list. They even tested two entries on that list.
They could even test drive a bunch of them and come with their own list. You cannot choose for them.

**Comment by jonjahren** [comment]
When I google the "best linux distro for gaming" I get two top results, and the toms guide one is absolute garbage. Listing Manjaro, Garuda and Drauger instead of the mainstream distributions like Fedora or openSUSE is really terrible advice. No one should follow that advice at all, it is close to being completely worthless.

**Comment by fleshin** [comment]
The list includes Ubuntu, Manjaro and PopOS. Those are pretty popular, but as I said before, this is a very subjective issue. 
It could be great for me, garbage for you and it is fine. They are professional reviewers, let them make their own list.

**Comment by jonjahren** [comment]
And of those three, I would only recommend one. A lot of LTTs issues came from insisting on using Manjaro or Pop. When you recommend a distro, you recommend everything about it. Infrastructure, bug triage, upstream connections, responsiveness to bug reports. If you claim that Manjaro or Pop does a better job at this than Fedora, backed by Red Hat and openSUSE then you are way too biased, and a simple look at my avatar shows that I am not a fan of either of those distributions. 

These niche distributions are okay-ish if you recommend to someone who already know what they're doing, but they are complete garbage compared to the bigger ones. And you need to put away your own preference and bias when you recommend.

**Comment by fleshin** [comment]
I totally agree and I would personally not recommend PopOS or even less Manjaro. For a beginner I would choose Ubuntu from that list as it easier/has less rough edges than Debian (my personal favorite). I am still frustrated they didn't include Ubuntu on their tests as the user base is larger and it would be easier to get help from the community. But again, even if we both agree, that would be subjective. We would need a poll of some kind to get more people represented or some an objective benchmark to rank them.

**Comment by fleshin** [comment]
Here is a poll with 15k votes. https://strawpoll.com/z57pyrzxw/r
It is funny because the results are almost exactly the opposite of what I would recommend.
Anyway, I think people answers from what they are using or what is best for their own instead of thinking what would would work best for a linux beginner that wants to play games and other basic stuff.

**Comment by fleshin** [comment]
I think the problem is to ask the right question. For advanced users wanting to get extra FPS, probably gentoo is a good option, For someone coming from windows and want a quick painless transition to their favorite games probably is not.
The gaming part can probably be boiled down to 1. support for proprietary drivers OOTB (sorry debian) and 2. Include key software on the default app stores such as steam, lutris, OBS, etc.

I think we can make a table (in the wiki perhaps?) listing the key features for most distros and let users decide.

**Comment by fleshin** [comment]
Here is a draft/attempt on an objective table to help new linux gamers choose their right distro: 

https://github.com/fleshin/ltt-linux-challenge-issues/wiki/Best-distro-for-gamers-transitioning-to-Linux-for-the-first-time

After some polishing/accuracy checking we could merge into this same repo. 
Please, let me know comments, corrections, etc Thanks!

**Comment by jharmer95** [comment]
@fleshin Lenovo laptops can officially come with Fedora pre-installed nowadays. Just a small correction

**Comment by fleshin** [comment]
Happy to hear that, table is updated now...  Thanks for the info!

**Comment by fleshin** [comment]
BTW, anyone knows any source for estimated user base for each distro? 
This is the hardest piece of info to get...

**Comment by glibg10b** [comment]
@fleshin Most distros don't collect telemetry by default. You could try the [Steam Hardware Survey](https://store.steampowered.com/hwsurvey?platform=linux) (click on "Linux Version"), but the results are biased because some distro users are more likely to use Steam and opt into the survey than others.
