### ISSUE TITLE
`The option to show Snap, Flatpak, and AUR packages in Pamac is "hidden".`

### ISSUE THREAD

**Issue by BLucky-gh** [glibg10b/ltt-linux-challenge-issues#20]
It would make sense to enable Flatpak by default, and show Snap and AUR packages when searched, but show a warning on the first install attempt:

- for snap: something that warns about the general issues that often arise with snap
- for AUR: a general warning about the fact that since manjaro delays the release of packages for a week or so, not all AUR packages will work.

**Comment by sorat0mo** [comment]
I suggest the option to enable flatpak, snap, and AUR on first startup of pamac, or installing Manjaro.

It could also be incorporated into other distros (snaps and flatpaks), during the installation process, available as additional components.
