### ISSUE TITLE
Compression—Nautilus 41.1-1 Cuts Off Compression Options

### ISSUE THREAD

**Issue by LunaGNUisance** [glibg10b/ltt-linux-challenge-issues#27]
![gnome-nautilus-compress-cutoff](https://user-images.githubusercontent.com/78894455/144846679-64c83c28-af47-47da-a0ea-c802ca4414c0.png)

You can see this in Gardiner Byrant's video as he attempts to compress the files. This is also present on my system in Arch Linux. Luke/Linus don't use Nautilus, so they don't face this issue.

Up to you whether you consider this out of scope or not.

**Comment by glibg10b** [comment]
Yep, out of scope. Please report it at https://gitlab.gnome.org/GNOME/nautilus/-/issues
