### ISSUE TITLE
Dolphin - Open as root

### ISSUE THREAD

**Issue by dm2912** [glibg10b/ltt-linux-challenge-issues#3]
There's an extension 

https://store.kde.org/p/1384645/

Which is kinda fine. If a user has the knowledge to install the extension, then they probably understand the risks or have a particular reason to use root. If they don't then they probably shouldnt be anyway

**Comment by dm2912** [comment]
And once you use it there is a clear warning that you are sudo 

![image](https://user-images.githubusercontent.com/25871666/144755467-9b4a81cd-e0e4-46fb-adb1-df9e4202f225.png)

**Comment by Chuhtra** [comment]
Tbh this has also bothered me in the past. I think the choice shown below should be somehow altered, as using root privileges as a normal user to open a directory in File Manager isn't the same with opening a directory as root user, but it is also not clear that this is the case.

![2021-12-05-185110_3840x1080_scrot](https://user-images.githubusercontent.com/40795688/144755788-5843806b-42a1-4b03-b5d7-2c2dd026b602.png)
.

**Comment by Sgt-Miller** [comment]
For nautilus, you can install nautilus-admin 
More details : https://askubuntu.com/questions/156998/how-do-i-start-nautilus-as-root

**Comment by dm2912** [comment]
All the dolphin addon does is add a "open as admin" option

![image](https://user-images.githubusercontent.com/25871666/144756546-7797faf0-9396-40ff-9355-24976efd91d3.png)

ultimately its something fairly easily achievable, but with enough to prevent a user who really doesnt know what they are doing doing damage
