### ISSUE TITLE
Compression utility should indicate status of compression in filename

### ISSUE THREAD

**Issue by FruityWelsh** [glibg10b/ltt-linux-challenge-issues#32]
Since it seems renaming it had no negative effects to the compression, it should instead be renamed by the compression utility to indicate status. I.E.: ```file.compressing[*---]``` and with progress ```file.compressing[**--]```. It should also check what the current main section of the name is and use that when renaming, allowing for a user to rename the first part without losing it on the next name update.

The option of simply hiding it, violates the principle of doing something when a user does something to indicate action and makes canceling via deletion a power user task instead of a normal option.

The option of a pop-up has two downsides:
1.  It could get lost
2. If it forced top level, it could get in the way of use on what could be a background task for the user

My personal preference for a filename based option is also so that I could potentially use this via cli instead of monitoring the file size changes.

**Comment by magnus-ISU** [comment]
Is it easy to write a program that changes the name with high frequency like this? If so that is an interesting idea.

**Comment by NicoWeio** [comment]
The `[]` characters won't work on some file systems though, right?

**Comment by FruityWelsh** [comment]
> The `[]` characters won't work on some file systems though, right?

hmm I was concerned for special characters in cli use, but I was not aware of filesystems that would lack support for them, do you have any examples?

**Comment by rossbridger** [comment]
As I mentioned earlier on reddit, it's rather more intuitive to show a progress bar on unfinished zip files (or half-copied files for that matter) to inform the users that the zipping/copying progress is not finished.

Possibly looks like this:

![application-zip](https://user-images.githubusercontent.com/10781734/145081258-04d93bcc-62ef-4fc9-bd9e-ec89394a1989.png)

**Comment by NicoWeio** [comment]
> do you have any examples?

I just looked it up. Popular examples of "problematic" filesystems are FAT12/16/32 not supporting `[]` and NTFS not supporting `*`. [Here](https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations) is a more comprehensive list.

**Comment by glibg10b** [comment]
@rossbridger It's being considered, but it'd be hard to implement (https://youtu.be/ENBu9_xTrWU?t=877)

**Comment by glibg10b** [comment]
Oops, didn't mean to close

**Comment by tjkrobertson** [comment]
The square brackets will 1000% cause problems in any script where you so much as look in the directory where that file exists.

**Comment by glibg10b** [comment]
@tjkrobertson Good scripts escape/quote filenames (otherwise spaces would also break them)

**Comment by tjkrobertson** [comment]
Last I checked, `ls` doesn't return a list of quoted files. If you use that on a file with square brackets in the filename, POSIX-compliant shells will bug out because they're the symbol that denotes an if statement.

**Comment by glibg10b** [comment]
@tjkrobertson That's what wildcards are for, they automatically escape weird characters and spaces

**Comment by glibg10b** [comment]
[Temp file names now have a .part suffix](https://invent.kde.org/utilities/ark/-/merge_requests/79)
