### ISSUE TITLE
Remove "Mouse acceleration is on by default"

### ISSUE THREAD

**Issue by luni3359** [glibg10b/ltt-linux-challenge-issues#35]
In the video Linus expresses his concern on how mouse acceleration is turned on by default but **mouse acceleration is on by default on Windows 10, probably ever since Windows XP**. On Mac OS you can't even turn off mouse acceleration without using a very specific terminal command for it.

This should be removed from the list because changing the default behavior will be detrimental rather than a welcome change.

**Turning mouse acceleration off by default will affect the majority of users as most people don't bother changing the defaults.**

**Comment by luni3359** [comment]
At the very least please add a note pointing out that there's feature-parity with Windows to not make Linux developers think it's an issue.

**Comment by glibg10b** [comment]
I'll remove it, thanks for the feedback
