### ISSUE TITLE
Compression appears to finish instantly when, in fact, it does not.

### ISSUE THREAD

**Issue by risingPhil** [glibg10b/ltt-linux-challenge-issues#36]
Hello,

On the main page of this repo, I saw that you listed this as a possible fix:

> Possible fix: Hide the archive (dot prefix) until it's done compressing.

I don't particularly agree with that one. The reason being that it removes any visual indication of the operation doing anything.

One of the things that made this an issue for Linus, was that the progress indication would be shown in the bottom right corner of his **second monitor**.

Worse still, this progress indication is usually hidden behind the spinning circle icon (notifications dropdown menu) in KDE (as far as I remember from my own system. Take this with a grain of salt, however, because I'm still using KDE version 5.12.8 as my (embedded) dev environment is stable at this point)

Possible fix: When such an action is triggered, expand the KDE "notifications dropdown menu" automatically by default on the screen the action was triggered. (but make it configurable)

That way, operation progress has an immediate visual indication and it nudges the user into checking the notifications dropdown menu for progress updates. Veteran users, however, could configure it to not bother them.

**Comment by glibg10b** [comment]
I added a link to [a discussion](https://invent.kde.org/teams/usability/issue-board/-/issues/4).
