### ISSUE TITLE
Github file download

### ISSUE THREAD

**Issue by muametgrooby** [glibg10b/ltt-linux-challenge-issues#38]
## Part 2

> When Linus tried to download a script from GitHub, the process was difficult, he ended up downloading it as HTML.

I developed a simple Firefox addon which adds the download button on every downloadable github file
https://addons.mozilla.org/en-US/firefox/addon/github-download-button-addon/
![screen1](https://user-images.githubusercontent.com/42146933/145686947-7e4daa50-06df-414b-8256-306b7bd7452a.png)
![screen2](https://user-images.githubusercontent.com/42146933/145686951-d11b408a-6876-4137-97c9-4be230feb8ce.png)

**Comment by NicoWeio** [comment]
That's nice, but I wouldn't consider installing a browser extension a fix, at least for users who are new to GitHub and don't know about the existence of such an extension. 🤔

**Comment by muametgrooby** [comment]
Apparently there's already a project doing the same thing, I'd recommend using this one instead of mine as I didn't spend too much time developing it
https://github.com/32Bites/LetsGet
