### ISSUE TITLE
no license 

### ISSUE THREAD

**Issue by SoftwareEthicsResearcher** [glibg10b/ltt-linux-challenge-issues#42]
Hello,

May we know the license for the repo? GitHub also encourages us to have a license for public repo (under "Licensing a repository - GitHub Docs"). We would like to highlight this as a transparency concern.

The following are from GitHub Docs.
· "If you're creating an open source project, we strongly encourage you to include an open source license."
· "If you publish your source code in a public repository on GitHub Enterprise Server, other users of your GitHub Enterprise Server instance have the right to view and fork your repository."
· "Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software."

Regards, Software Ethics Researcher.

**Comment by glibg10b** [comment]
Thanks for reminding me. I added the MIT license: https://github.com/glibg10b/ltt-linux-challenge-issues/blob/main/LICENSE.md

**Comment by NicoWeio** [comment]
For future reference: 589e80f75cea09ef2b41143e6b1f8bb209366dc4
