### ISSUE TITLE
 Scrolling with the mouse wheel in KDE's volume mixer applet scrolls through both devices and levels of devices.

### ISSUE THREAD

**Issue by alou-S** [glibg10b/ltt-linux-challenge-issues#6]
This is a old issue. I faced it too. It is fixed.

Currently works perfectly with my 3 sinks and 2 devices

**Comment by Mitsunee** [comment]
I've been using KDE since Kubuntu 19.04 and have not come across this issue before, so it's probably fixed and they ran into an older version here.
