### ISSUE TITLE
NVENC does show as option in obs

### ISSUE THREAD

**Issue by Monsterovich** [glibg10b/ltt-linux-challenge-issues#8]
![изображение](https://user-images.githubusercontent.com/3750982/144757046-184cd36c-a30c-4bf6-ba31-021c6525d125.png)

```
lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Linuxmint
Description:	Linux Mint 20.2
Release:	20.2
Codename:	uma
```

![изображение](https://user-images.githubusercontent.com/3750982/144757077-58329c2c-03ac-4ccb-8a8b-bc9342e9f288.png)

What am I doing wrong?

**Comment by glibg10b** [comment]
I think it's about a new version of NVENC, but I removed it anyway.
