### ISSUE TITLE
OBS requires a restart (or something) for some things to work correctly, but doesn't say so.

### ISSUE THREAD

**Issue by alou-S** [glibg10b/ltt-linux-challenge-issues#9]
So basically Windows has the need for restarting after updates since they can't be installed when the OS is running. And Linux doesn't really need a restart unless you need the kernel updates to be applied right now (`livepatch` can solve that too)  

But the misconception that Linux doesn't need restarts to fix problems is not true. Of course alot of problems can be fixed without restarting but will often require you to debug it first and then fixing it.
Re initializing a program is way faster than debugging so go for it.
Also new configuration is loaded when you restart the program.

I mean most routers are based on Linux and a good old restart fixes your network issues. most of the time :)

**Comment by glibg10b** [comment]
I agree with you and don't agree with Linus either, but I think OBS should tell you to restart at least instead of just behaving strangely.
